name = "event-api"
main = "src/index.js"
compatibility_date = "2024-01-28"

# Production environment
[vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = ""

[[d1_databases]]
binding = "DB"
database_name = "event-db"
database_id = "dba64ea5-dae4-4ed9-8ad1-6ff3bd25b263"

# Development environment
[env.dev]
name = "event-api-dev"

[env.dev.vars]
ENVIRONMENT = "development"
CLOUDFLARE_ACCOUNT_ID = "6ef191c25141298c09bb2f0d926dce50"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "event-db-dev"
database_id = "c132d90d-402f-4db7-9c42-f79347bf6988"